### ISSUE TITLE
Duvidas no printf

### ISSUE THREAD

**Issue by PYROP3** [CaioTorre/Projeto-Estruturas-A#2]
Imprimir matrizes que possuam elementos >99 faz com que os numeros sejam impressos "juntos"
```
[DEBUG] Lista: (DIVMAT lin:3 col:4) (SOMAMAT lin:3 col:4) (MAT2 lin:3 col:4) (MAT1T lin:4 col:3) (MAT1 lin:3 col:4) 
ME MAT1 MAT2 MULTEMAT
Multiplicar matrizes elemento a elemento

  1.00  4.00  9.00 16.00
 25.00 36.00 49.00 64.00
 81.00100.00121.00144.00

[DEBUG] Lista: (MULTEMAT lin:3 col:4) (DIVMAT lin:3 col:4) (SOMAMAT lin:3 col:4) (MAT2 lin:3 col:4) (MAT1T lin:4 col:3) (MAT1 lin:3 col:4)
```
Seria esse o comportamento esperado?

**Comment by marcosatsf** [comment]
Segundo o Edmar, deveríamos fazer os "printfs" utilizando a tag %6.2, porém ao usar o número 6, o programa conta o '.' e os dígitos do ponto flutuante restanto somente 3 espaços vazios para serem preenchidos pelos dígitos inteiros, por isso os números saem todos juntos. O que poderíamos fazer é realmente deixar 6 dígitos inteiros trocando a tag para %9.2

**Comment by PYROP3** [comment]
O problema acaba sendo que se ele fizer uma verificacao estilo URI, a gente tem que deixar o `%6.2f` mesmo, que e o que ele disse

**Comment by marcosatsf** [comment]
Então deixamos e fazemos essa última pergunta na segunda-feira

**Comment by PYROP3** [comment]
É, deixa desse jeito feio mesmo
